### ISSUE TITLE
Deprecated selector in  language-whitespace/styles/language-whitespace.less 

### ISSUE THREAD

**Issue by maalston** [veniversum/language-whitespace#1]
In  language-whitespace/styles/language-whitespace.less :  Starting from Atom v1.13.0, the contents of  atom-text-editor  elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using  :host  and  ::shadow  pseudo-selectors, and prepend all your syntax selectors with  syntax- . To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors: *  atom-text-editor .whitespace.char.tab, atom-text-editor::shadow .whitespace.char.tab  =>  atom-text-editor .whitespace.char.tab, atom-text-editor.editor .syntax-whitespace.syntax-char.syntax-tab  *  atom-text-editor .whitespace.char.space, atom-text-editor::shadow .whitespace.char.space  =>  atom-text-editor .whitespace.char.space, atom-text-editor.editor .syntax-whitespace.syntax-char.syntax-space  *  atom-text-editor .invisible-character, atom-text-editor::shadow .invisible-character  =>  atom-text-editor .invisible-character, atom-text-editor.editor .invisible-character  Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by veniversum** [comment]
Fixed in v1.2.0
